/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.tss.campionatorugby;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tss
 */
public class WinRugby extends javax.swing.JFrame {

    static ArrayList<Squadra> listasquadre = new ArrayList<>();
    static ArrayList<Partita> listapartite = new ArrayList<>();

    /**
     * Creates new form WinRugby
     */
    public WinRugby() {
        initComponents();
        this.setLocationRelativeTo(null);//per piazzare finestra in centro
        caricaDatiSquadre();
        showSquadre();
        caricaDatiPartite();
        showPartite();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txNomeSquadra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txSede = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btNewSquadra = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        lblMsgErr = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpElencoSquadre = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        txgiornata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txSquadra1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpElencoGiornate = new javax.swing.JTextPane();
        btNewPartita = new javax.swing.JButton();
        txSquadra2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txMetesq1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txMetesq2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(64, 188, 19));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Squadra");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setText("nome");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setText("sede");

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Elenco squadre");

        btNewSquadra.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btNewSquadra.setText("NEW");
        btNewSquadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewSquadraActionPerformed(evt);
            }
        });

        btUpdate.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btUpdate.setText("UPDATE");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        lblMsgErr.setBackground(new java.awt.Color(133, 255, 55));

        jScrollPane2.setViewportView(tpElencoSquadre);

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Partita");

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setText("Giornata");

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setText("Sq1");

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Elenco Giornate");

        jScrollPane3.setViewportView(tpElencoGiornate);

        btNewPartita.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btNewPartita.setText("NEW");
        btNewPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewPartitaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel9.setText("Sq2");

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel10.setText("Mete1");

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel11.setText("Mete2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMsgErr, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btNewSquadra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(txNomeSquadra, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(txSede))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(21, 21, 21)
                                            .addComponent(txgiornata, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txSquadra1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel10))
                                                    .addGap(21, 21, 21)
                                                    .addComponent(txSquadra2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txMetesq1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(btNewPartita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(151, 151, 151))
                                        .addComponent(txMetesq2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                    .addComponent(txNomeSquadra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txSede, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(btNewSquadra)
                                .addGap(18, 18, 18)
                                .addComponent(btUpdate))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txgiornata, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSquadra1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSquadra2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txMetesq1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txMetesq2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btNewPartita))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(lblMsgErr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btNewSquadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewSquadraActionPerformed
        // legge dati nuova squadra

        String squadra = txNomeSquadra.getText();
        String sede = txSede.getText();
        Squadra sq = new Squadra(squadra, sede);
        listasquadre.add(sq);
        salvaSquadreCSV();
        showSquadre();
        pulisciSquadra();
    }//GEN-LAST:event_btNewSquadraActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btNewPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewPartitaActionPerformed

        int giornata = Integer.parseInt(txgiornata.getText());
        String squadra1 = txSquadra1.getText();
        String squadra2 = txSquadra2.getText();
        int mete1 = Integer.parseInt(txMetesq1.getText());
        int mete2 = Integer.parseInt(txMetesq2.getText());
        Partita par = new Partita(giornata, squadra1, squadra2, mete1, mete2);
        listapartite.add(par);
        salvaPartiteCSV();
        showPartite();
        pulisciPartita();

    }//GEN-LAST:event_btNewPartitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinRugby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinRugby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinRugby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinRugby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinRugby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNewPartita;
    private javax.swing.JButton btNewSquadra;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMsgErr;
    private javax.swing.JTextPane tpElencoGiornate;
    private javax.swing.JTextPane tpElencoSquadre;
    private javax.swing.JTextField txMetesq1;
    private javax.swing.JTextField txMetesq2;
    private javax.swing.JTextField txNomeSquadra;
    private javax.swing.JTextField txSede;
    private javax.swing.JTextField txSquadra1;
    private javax.swing.JTextField txSquadra2;
    private javax.swing.JTextField txgiornata;
    // End of variables declaration//GEN-END:variables

    private void caricaDatiSquadre() {

        try {
            //aprire il file /tss/Scuola/datiocsv
            File file = new File("");
            String pathfile = file.getCanonicalPath();
            File filecsv = new File(pathfile + "/dati/squadre.csv");
            //creo scanner
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta (creo scanner
            int n = 1;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (n > 1) {
                    String dati[] = riga.split(";");
                    String squa = dati[0];
                    String sede = dati[1];

                    Squadra s = new Squadra(squa, sede);
                    listasquadre.add(s);
                }
                n++;
            }

        } catch (Exception e) {

        }

    }

    private void showSquadre() {

        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display una volta avuto tutto
        String testoDisplay = "";
        for (int i = 0; i < listasquadre.size(); i++) {
            Squadra sq = listasquadre.get(i);
            String info = sq.getInfo();
            testoDisplay = testoDisplay + info;
        }
        //visualizzo tutti insieme i dati sul display creato
        tpElencoSquadre.setText(testoDisplay);
    }

    private void pulisciSquadra() {
        txNomeSquadra.setText("");
        txSede.setText("");
    }

   
    private void salvaSquadreCSV() {
        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display una volta avuto tutto
        String intestazione = "Squadra;Sede;\n";
        String dati = "";
        for (int i = 0; i < listasquadre.size(); i++) {
            Squadra sq = listasquadre.get(i);
            String riga = sq.getCSV();
            dati += riga;
        }
        String txtFile = intestazione + dati;
        //creo file corsi .txt e ci scrivo dentro
        //testo disply e lo chiudo se no si blocca

        try {
            //creo file squadre.csv
            File file = new File("");
            String pathfile = file.getCanonicalPath();
            FileWriter myWriter = new FileWriter(pathfile + "/dati/squadre.csv");
            myWriter.write(txtFile);
            myWriter.close();
        } catch (IOException ex) {
            lblMsgErr.setText("Errore di scrittura nel file squadre.csv");
        }

    }

    private void caricaDatiPartite() {

        try {
            //aprire il file /tss/Scuola/datiocsv
            File file = new File("");
            String pathfile = file.getCanonicalPath();
            File filecsv = new File(pathfile + "/dati/partite.csv");
            //creo scanner
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta (creo scanner
            int n = 1;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (n > 1) {
                    String dati[] = riga.split(";");
                    int giorn = Integer.parseInt(dati[0]);
                    String sq1 = dati[1];
                    String sq2 = dati[2];
                    int mtsq1 = Integer.parseInt(dati[3]);
                    int mtsq2 = Integer.parseInt(dati[4]);

                    Partita p = new Partita(giorn, sq1, sq2, mtsq1, mtsq2);
                    listapartite.add(p);
                }
                n++;
            }

        } catch (Exception e) {

        }

    }

    private void showPartite() {

        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display una volta avuto tutto
        String testoDisplay = "";
        for (int i = 0; i < listapartite.size(); i++) {
            Partita par = listapartite.get(i);
            String info = par.getInfoPartita();
            testoDisplay = testoDisplay + info;
        }
        //visualizzo tutti insieme i dati sul display creato
        tpElencoGiornate.setText(testoDisplay);
    }

    private void pulisciPartita() {
        txgiornata.setText("");
        txSquadra1.setText("");
        txSquadra2.setText("");
        txMetesq1.setText("");
        txMetesq2.setText("");
    }

    /*private void refreshLista() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < listasquadre.size(); i++) {
            Squadra s = listasquadre.get(i);
            String item = s.getNome() + s.getSede();
            model.addElement(item);
        }
        lstSquadre.setModel(model);

    }*/
    private void salvaPartiteCSV() {
        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display una volta avuto tutto
        String intestazione = "Giornata;Squadra1;Squadra2;MeteSq1;Metesq2\n";
        String dati = "";
        for (int i = 0; i < listapartite.size(); i++) {
            Partita part = listapartite.get(i);
            String riga = part.getCSVPartita();
            dati += riga;
        }
        String txtFile = intestazione + dati;
        //creo file corsi .txt e ci scrivo dentro
        //testo disply e lo chiudo se no si blocca

        try {
            //creo file squadre.csv
            File file = new File("");
            String pathfile = file.getCanonicalPath();
            FileWriter myWriter = new FileWriter(pathfile + "/dati/partite.csv");
            myWriter.write(txtFile);
            myWriter.close();
        } catch (IOException ex) {
            lblMsgErr.setText("Errore di scrittura nel file partite.csv");
        }

    }

}
