/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionescuola;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tss
 */
public class WinGestione extends javax.swing.JFrame {
// aggiungo lo stato statico perchè questa è la classe principale e l'elenco corsi
    //deve essere fisso e usato da altri oggetti

    static ArrayList<Corso> listacorsi = new ArrayList<Corso>();
    static ArrayList<Anagrafica> listaAnagrafiche = new ArrayList<Anagrafica>();
    int idcorso = -1;//indico meno 1 perchè evidente non selezionato nulla

    /**
     * Creates new form WinGestione
     */
    public WinGestione() {
        initComponents();
        this.setLocationRelativeTo(null);//per piazzare finestra in centro
        caricaDatiCorsi();
        showCorsi();
        caricaDatiAnagrafica();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpDisplay = new javax.swing.JTextPane();
        btnGestioneCorsi = new javax.swing.JButton();
        btGestAnagrafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitolo.setFont(new java.awt.Font("Cantarell", 3, 22)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Gestione scuola");

        jScrollPane2.setViewportView(tpDisplay);

        btnGestioneCorsi.setText("Gestione Corsi:");
        btnGestioneCorsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioneCorsiActionPerformed(evt);
            }
        });

        btGestAnagrafica.setText("Gestione anagrafiche");
        btGestAnagrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGestAnagraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestioneCorsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGestAnagrafica, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGestioneCorsi)
                        .addGap(28, 28, 28)
                        .addComponent(btGestAnagrafica))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestioneCorsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioneCorsiActionPerformed
        // TODO add your handling code here:
        // Dialog necessita di parametri: this sono io che apro, true vuol dire
        //che non puoi fare altro fino a che non chiudi la finestra
        new WinDialogCorsi(this, true).setVisible(true);
    }//GEN-LAST:event_btnGestioneCorsiActionPerformed

    private void btGestAnagraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGestAnagraficaActionPerformed
        // TODO add your handling code here:
        //apertura finestra dialogo per caricamento e gestione anagrafica
        new WinDialogAnagrafica(this, true).setVisible(true);

    }//GEN-LAST:event_btGestAnagraficaActionPerformed
    /**
     * chiamo questo metodo quando ho
     */
    private void showCorsi() {
        //recupero un corso per volta
        //estraggo info tipo string
        //aggiungo info a un testo generico che poi setto in display una volta avuto tutto
        String testoDisplay = "";
        for (int i = 0; i < listacorsi.size(); i++) {
            Corso cor = listacorsi.get(i);
            String info = "[" + (i + 1) + "] " + cor.getInfo();
            testoDisplay = info + testoDisplay;
        }
        //visualizzo tutti insieme i dati sul display creato
        tpDisplay.setText(testoDisplay);
    }

    private void caricaDatiCorsi() {
        try {
            //aprire il file /tss/Scuola/datiocsv
            File filecsv = new File("/home/tss/Scuola/corsi.csv");
            //creo scanner
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta (creo scanner
            int n = 1;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (n > 1) {
                    String dati[] = riga.split(";");
                    //dati [0] + nome corso, dati [1] durata etc
                    String nc = dati[0];
                    int dur = Integer.parseInt(dati[1]);
                    String des = dati[2];
                    String d[] = dati[3].split("-");
                    int y = Integer.parseInt(d[0]);
                    int m = Integer.parseInt(d[1]);
                    int g = Integer.parseInt(d[2]);
                    String link = dati[4];
                    Corso c = new Corso(nc, dur, y, m, g);
                    c.setDescrizione(des);
                    c.setLink(link);
                    //il corso è pronto
                    listacorsi.add(c);
                }
                n++;
            }

        } catch (Exception e) {

        }
        
    }  

    private void caricaDatiAnagrafica() {
        try {
            //aprire il file /tss/Scuola/datiocsv
            File filecsv = new File("/home/tss/Scuola/anagrafica.csv");
            //creo scanner
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta (creo scanner
            int n = 1;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (n > 1) {
                    String dati[] = riga.split(";");
                    int id = Integer.parseInt(dati[0]);
                    String cog = dati[1];
                    String nom = dati[2];
                    String mail = dati[3];

                    Anagrafica a = new Anagrafica(id, cog, nom, mail);
                    listaAnagrafiche.add(a);
                }
                n++;
            }

        } catch (Exception e) {

        }

        //la riga la taglio in tanti pezzi con il ; in un array
        //elemento per elemento dell'array lo imposto ad un corso
        //il corso lo aggiungo alla lista e così via per le altre righe del file
        //alla fine chiudo il file
    }

    public static int getNewAnagrafica() {

        int newId = 1;
        //parto con l'idea che il mio ID sia 1 ma se non ce ne sono ancora tolgo 1
        //e parto da zero. Se ci sono già dei record
        if (listaAnagrafiche.size() > 0) {
            //int lastIndex= listaAnagrafiche.size()-1; e sotto get(lastindex)
            newId = listaAnagrafiche.get(listaAnagrafiche.size() - 1).getId_anagrafica() + 1;
        }
        return newId;
    }

// recuperiamo dati da interfaccia
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinGestione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGestAnagrafica;
    private javax.swing.JButton btnGestioneCorsi;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JTextPane tpDisplay;
    // End of variables declaration//GEN-END:variables
}
