/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gestionescuola;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DateFormatter;

/**
 *
 * @author tss
 */
public class WinGestione extends javax.swing.JFrame {

    static ArrayList<Corso> listacorsi = new ArrayList<Corso>();
    static ArrayList<Anagrafica> listaAnagrafiche
            = new ArrayList<Anagrafica>();
    int idcorso = -1;

    /**
     * Creates new form WinGestione
     */
    public WinGestione() {
        initComponents();
        this.setLocationRelativeTo(null);
        caricaDatiAnagrafica();
        caricaDatiCorsi();
        showCorsi();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpDisplay = new javax.swing.JTextPane();
        btnGetionecorsi = new javax.swing.JButton();
        btnGestAnagrafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblTitolo.setFont(new java.awt.Font("Cantarell", 3, 22)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Gestione scuola");

        jScrollPane1.setViewportView(tpDisplay);

        btnGetionecorsi.setText("Gestione Corsi");
        btnGetionecorsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetionecorsiActionPerformed(evt);
            }
        });

        btnGestAnagrafica.setText("Gestione Anagrafiche");
        btnGestAnagrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestAnagraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGetionecorsi, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(btnGestAnagrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGetionecorsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGestAnagrafica))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetionecorsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetionecorsiActionPerformed
        // TODO add your handling code here:
        new winDialogCorsi(this, true).setVisible(true);

    }//GEN-LAST:event_btnGetionecorsiActionPerformed

    private void btnGestAnagraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestAnagraficaActionPerformed
        // TODO add your handling code here:
        // apertura finbestyra dialogo per caricamento e gestione anagrafica
        new WinDialogAnagrafica(this, true).setVisible(true);


    }//GEN-LAST:event_btnGestAnagraficaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        showCorsi();
    }//GEN-LAST:event_formWindowActivated
    /**
     * aggiorna lista corsi in display
     */
    private void showCorsi() {
        // recupero un corso per volta
        // estraggo info tipo string
        // aggiungo info a un testo generico che poi setto in display
        String testoDisplay = "";
        for (int i = 0; i < listacorsi.size(); i++) {
            // recupero un corso per volta
            Corso c = listacorsi.get(i);
            String info = "[" + (i + 1) + "] " + c.getInfo();
            testoDisplay = info + testoDisplay;
        }
        //visualizzo i corsi in display
        tpDisplay.setText(testoDisplay);
    }

    private void caricaDatiCorsi() {
        try {
            //aprire il file /tss/sScuola/dati.csv
            File filecsv = new File("/home/tss/Scuola/corsi.csv");
            //creo scanner per lelggere una riga per volta
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta
            int n = 1;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (n > 1) {
                    String[] dati = riga.split(";");
                    //dati[0] nomecorso dati[1] durata etc etc
                    String nc = dati[0];
                    int durata = Integer.parseInt(dati[1]);
                    String des = dati[2];
                    String d[] = dati[3].split("-");
                    int y = Integer.parseInt(d[0]);
                    int m = Integer.parseInt(d[1]);
                    int g = Integer.parseInt(d[2]);
                    String link = "";
                    if (dati.length >= 5) { //se lungo almeno 5 ho il link
                        link = dati[4];
                    }
                    ////
                    Corso c = new Corso(nc, durata, y, m, g);
                    if (dati.length >= 6) { //se lungo 6 ho gli iscritti
                        String registro = dati[5]; // "1,4,7"
                        String[] regID = registro.split(",");// array ["1","4"...]
                        for (String sid : regID) {
                            //indice anagrafica
                            int id = Integer.parseInt(sid);// id= 1 id = 4 ...
                            Anagrafica al = getAlunnoById(id);
                            c.insertAlunno(al);
                        }
                    }
                    ////

                    //il corso e' pronto lo aggiungiamo alla lista
                    listacorsi.add(c);
                }
                n++;
                //la riga la taglio in tanti pezzi col ; in un array
                // elmento per lelemnto dell'array lo imposto ad un corso
                //il corso lo aggiungo alla lista 
            }
            //e cosi' via per le altre righe del file'
            //alla fine chiudo il file se no si blocca

        } catch (Exception e) {

        }

    }

    private void caricaDatiAnagrafica() {
        try {
            //aprire il file /tss/sScuola/dati.csv
            File filecsv = new File("/home/tss/Scuola/anagrafica.csv");
            //creo scanner per lelggere una riga per volta
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta
            int n = 1;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (n > 1) {
                    String[] dati = riga.split(";");
                    //id:cognome;nome;mail
                    int id = Integer.parseInt(dati[0]);
                    String cog = dati[1];
                    String nom = dati[2];
                    String mail = dati[3];
                    Anagrafica a = new Anagrafica(id, cog, nom, mail);
                    listaAnagrafiche.add(a);
                }
                n++;
                //la riga la taglio in tanti pezzi col ; in un array
                // elmento per lelemnto dell'array lo imposto ad un corso
                //il corso lo aggiungo alla lista 
            }
            //e cosi' via per le altre righe del file'
            //alla fine chiudo il file se no si blocca

        } catch (Exception e) {

        }

    }

    public static int getNewIdAnagrafica() {
        int newId = 1;
        if (listaAnagrafiche.size() > 0) {
            int lastindex = listaAnagrafiche.size() - 1;
            newId = listaAnagrafiche.get(lastindex).getId_anagrafica() + 1;
        }
        return newId;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinGestione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinGestione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestAnagrafica;
    private javax.swing.JButton btnGetionecorsi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JTextPane tpDisplay;
    // End of variables declaration//GEN-END:variables

    static public Anagrafica getAlunnoById(int id) {
        for (Anagrafica a : listaAnagrafiche) {
            if (id == a.getId_anagrafica()) {
                return a;
            }
        }
        return null;
    }
}
